[2019-09-26 09:00:07 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-26 09:00:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-26 09:00:07 +0000] [1] [INFO] Using worker: gevent
[2019-09-26 09:00:07 +0000] [8] [INFO] Booting worker with pid: 8
[2019-09-26 09:00:07 +0000] [9] [INFO] Booting worker with pid: 9
[2019-09-26 09:00:07 +0000] [10] [INFO] Booting worker with pid: 10
[2019-09-26 09:00:07 +0000] [11] [INFO] Booting worker with pid: 11
[2019-09-26 09:00:07 +0000] [12] [INFO] Booting worker with pid: 12
[2019-09-26 09:00:08 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/purchase.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'
[2019-09-26 09:00:08 +0000] [9] [INFO] Worker exiting (pid: 9)
[2019-09-26 09:00:08 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/purchase.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'
[2019-09-26 09:00:08 +0000] [8] [INFO] Worker exiting (pid: 8)
[2019-09-26 09:00:08 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/purchase.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'
[2019-09-26 09:00:08 +0000] [10] [INFO] Worker exiting (pid: 10)
[2019-09-26 09:00:08 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/purchase.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'
[2019-09-26 09:00:08 +0000] [11] [INFO] Worker exiting (pid: 11)
[2019-09-26 17:20:49 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-26 17:20:49 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-26 17:20:49 +0800] [1] [INFO] Using worker: gevent
[2019-09-26 17:20:49 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-26 17:20:49 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-26 17:20:49 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-26 17:20:49 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-26 17:20:49 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-26 17:26:58 +0800] [1] [INFO] Handling signal: term
[2019-09-26 17:26:58 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-26 17:26:59 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-26 17:26:59 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-26 17:26:59 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-26 17:26:59 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-26 17:26:59 +0800] [1] [INFO] Shutting down: Master
[2019-09-26 17:28:02 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-26 17:28:02 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-26 17:28:02 +0800] [1] [INFO] Using worker: gevent
[2019-09-26 17:28:02 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-26 17:28:02 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-26 17:28:02 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-26 17:28:02 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-26 17:28:03 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-26 17:28:05 +0800] [1] [INFO] Handling signal: term
[2019-09-26 17:28:06 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-26 17:28:06 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-26 17:28:06 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-26 17:28:06 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-26 17:28:06 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-26 17:28:06 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 10:39:10 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 10:39:10 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 10:39:10 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 10:39:10 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 10:39:10 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 10:39:10 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 10:39:10 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 10:39:10 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 10:42:17 +0800] [1] [INFO] Handling signal: term
[2019-09-27 10:42:17 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 10:42:18 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 10:42:18 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 10:42:18 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 10:42:18 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 10:42:18 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 11:10:30 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 11:10:30 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 11:10:30 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 11:10:30 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 11:10:30 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 11:10:31 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 11:10:31 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 11:10:31 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 11:29:54,816] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.5/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.5/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "/usr/local/lib/python3.5/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd9326bf160>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='order.service.consul', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9326bf160>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/purchase.py", line 15, in get_purchase
    response = requests.get(url)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='order.service.consul', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9326bf160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2019-09-27 11:31:40,809] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/site-packages/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.5/site-packages/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.5/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "/usr/local/lib/python3.5/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd9326c50b8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='order.service.consul', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9326c50b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/purchase.py", line 15, in get_purchase
    response = requests.get(url)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='order.service.consul', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9326c50b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2019-09-27 11:54:37 +0800] [1] [INFO] Handling signal: term
[2019-09-27 11:54:38 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 11:54:38 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 11:54:38 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 11:54:38 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 11:54:38 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 11:54:38 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 12:18:05 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 12:18:05 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 12:18:05 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 12:18:05 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 12:18:05 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 12:18:05 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 12:18:05 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 12:18:05 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 13:32:17 +0800] [1] [INFO] Handling signal: term
[2019-09-27 13:32:17 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 13:32:17 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 13:32:18 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 13:32:18 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 13:32:18 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 13:32:18 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 13:52:15 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 13:52:15 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 13:52:15 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 13:52:15 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 13:52:15 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 13:52:15 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 13:52:15 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 13:52:15 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 13:54:34 +0800] [1] [INFO] Handling signal: term
[2019-09-27 13:54:34 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 13:54:35 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 13:54:35 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 13:54:35 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 13:54:35 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 13:54:35 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 14:05:31 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 14:05:31 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 14:05:31 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 14:05:31 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 14:05:31 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 14:05:31 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 14:05:31 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 14:05:31 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 14:07:50 +0800] [1] [INFO] Handling signal: term
[2019-09-27 14:07:51 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 14:07:51 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 14:07:51 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 14:07:51 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 14:07:51 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 14:07:51 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 14:13:52 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 14:13:52 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 14:13:52 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 14:13:52 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 14:13:52 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 14:13:52 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 14:13:53 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 14:13:53 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 14:24:20 +0800] [1] [INFO] Handling signal: term
[2019-09-27 14:24:20 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 14:24:20 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 14:24:20 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 14:24:20 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 14:24:21 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 14:24:21 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 14:28:24 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 14:28:24 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 14:28:24 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 14:28:24 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 14:28:24 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 14:28:24 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 14:28:24 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 14:28:24 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:01:30 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:01:30 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:01:30 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:01:30 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:01:30 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:01:30 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:01:30 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:07:21 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:07:21 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:07:21 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:07:21 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:07:21 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:07:21 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:07:21 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:07:21 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:18:02 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:18:02 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:18:02 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:18:02 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:18:02 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:18:03 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:18:03 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:21:15 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:21:15 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:21:15 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:21:15 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:21:15 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:21:15 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:21:15 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:21:15 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:31:15 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:31:16 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:31:16 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:31:16 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:31:16 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:31:16 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:31:16 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:37:18 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:37:18 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:37:18 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:37:18 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:37:19 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:37:19 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:37:19 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:37:19 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:38:32 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:38:32 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:38:32 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:38:32 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:38:32 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:38:33 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:38:33 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:41:43 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:41:43 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:41:43 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:41:43 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:41:43 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:41:43 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:41:43 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:41:43 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:42:15 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:42:16 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:42:16 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:42:16 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:42:16 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:42:16 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:42:16 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:50:15 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:50:15 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:50:15 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:50:15 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:50:15 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:50:15 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:50:15 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:50:15 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 15:54:06 +0800] [1] [INFO] Handling signal: term
[2019-09-27 15:54:06 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 15:54:06 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 15:54:06 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 15:54:06 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 15:54:06 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 15:54:06 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 15:55:40 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 15:55:40 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 15:55:40 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 15:55:40 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 15:55:40 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 15:55:40 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 15:55:40 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 15:55:40 +0800] [12] [INFO] Booting worker with pid: 12
[2019-09-27 16:15:02 +0800] [1] [INFO] Handling signal: term
[2019-09-27 16:15:02 +0800] [9] [INFO] Worker exiting (pid: 9)
[2019-09-27 16:15:02 +0800] [10] [INFO] Worker exiting (pid: 10)
[2019-09-27 16:15:02 +0800] [12] [INFO] Worker exiting (pid: 12)
[2019-09-27 16:15:02 +0800] [11] [INFO] Worker exiting (pid: 11)
[2019-09-27 16:15:03 +0800] [8] [INFO] Worker exiting (pid: 8)
[2019-09-27 16:15:03 +0800] [1] [INFO] Shutting down: Master
[2019-09-27 16:17:43 +0800] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-27 16:17:43 +0800] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-27 16:17:43 +0800] [1] [INFO] Using worker: gevent
[2019-09-27 16:17:43 +0800] [8] [INFO] Booting worker with pid: 8
[2019-09-27 16:17:43 +0800] [9] [INFO] Booting worker with pid: 9
[2019-09-27 16:17:43 +0800] [10] [INFO] Booting worker with pid: 10
[2019-09-27 16:17:43 +0800] [11] [INFO] Booting worker with pid: 11
[2019-09-27 16:17:43 +0800] [12] [INFO] Booting worker with pid: 12
